Instance: add missing include after dfadaf29e779
Core/Instance.cpp:148:55: error: use of undeclared identifier 'S_IRUSR'
        hIDMapFile = shm_open(ID_SHM_NAME, O_CREAT | O_RDWR, S_IRUSR | S_IWUSR);
                                                             ^
Core/Instance.cpp:148:65: error: use of undeclared identifier 'S_IWUSR'
        hIDMapFile = shm_open(ID_SHM_NAME, O_CREAT | O_RDWR, S_IRUSR | S_IWUSR);
                                                                       ^