Instance: add missing headers more POSIX systems
Core/Instance.cpp:90:56: error: use of undeclared identifier 'PROT_READ'
        InstanceInfo *buf = (InstanceInfo *)mmap(0, BUF_SIZE, PROT_READ | PROT_WRITE, MAP_SHARED, hIDMapFile, 0);
                                                              ^
Core/Instance.cpp:90:68: error: use of undeclared identifier 'PROT_WRITE'
        InstanceInfo *buf = (InstanceInfo *)mmap(0, BUF_SIZE, PROT_READ | PROT_WRITE, MAP_SHARED, hIDMapFile, 0);
                                                                          ^
Core/Instance.cpp:90:80: error: use of undeclared identifier 'MAP_SHARED'
        InstanceInfo *buf = (InstanceInfo *)mmap(0, BUF_SIZE, PROT_READ | PROT_WRITE, MAP_SHARED, hIDMapFile, 0);
                                                                                      ^
Core/Instance.cpp:91:13: error: use of undeclared identifier 'MAP_FAILED'
        if (buf == MAP_FAILED) {
                   ^
Core/Instance.cpp:147:37: error: use of undeclared identifier 'O_CREAT'
        hIDMapFile = shm_open(ID_SHM_NAME, O_CREAT | O_RDWR, 0);
                                           ^
Core/Instance.cpp:147:47: error: use of undeclared identifier 'O_RDWR'
        hIDMapFile = shm_open(ID_SHM_NAME, O_CREAT | O_RDWR, 0);
                                                     ^
Core/Instance.cpp:185:3: error: use of undeclared identifier 'shm_unlink'
                shm_unlink(ID_SHM_NAME);     // If program exited or crashed before unlinked the shared memory object and it's contents will persist.
                ^